query UserMeByInstitute {
    userMe {
        id
        name
        phoneNumber
        birthDate
        credit {
            balance
        }
        authorities {
            authorityName
        }
        institutes {
            id
            name
        }
    }
}