query UserMeByParent {
    userMe {
        id
        name
        phoneNumber
        birthDate
        credit {
            balance
        }
        authorities {
            authorityName
        }
        children {
            id
            name
            phoneNumber
            birthDate
        }
    }
}